import Head from "next/head";
import React from "react";
import {
  Container,
  Description,
  Inner,
  Featured,
  İconWrap,
  Divider,
} from "../styles/Index.styled.js";
import { FeaturedProject } from "../src/components/FeaturedProject";
import { LinkedinIcon, GithubIcon } from "../styles/GlobalStyle";

export default function Home() {
  return (
    <>
      <Head>
        <title>Berat Genç | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <Inner>
          <Description>
            <h1>
              Developer creating digital tools and thoughtful, intuitive
              interfaces.
            </h1>

            <span>
              I'm Berat Genç, <span>Istanbul|TR </span> based self taught Front
              End Developer. I pay special attention to design to deliver
              holistic, engaging & approachable application interfaces with my
              graphic design background.
            </span>

            <span>
              Here you can explore visually pleasing seamless user interfaces
              backed with <span>concise&clean</span> code structure. You can
              check my socials here:
            </span>

            <İconWrap>
              <a href="https://www.linkedin.com/in/berat-gen%C3%A7-2a90b2214/">
                {LinkedinIcon}
              </a>
              <a href="https://github.com/soberbat">{GithubIcon}</a>
            </İconWrap>

            <Divider />
          </Description>

          <Featured>
            <FeaturedProject />
          </Featured>
        </Inner>
      </Container>
    </>
  );
}
